# Generated by Django 3.0.5 on 2021-03-24 17:43

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('label', models.TextField(default='THIS IS A LABEL FOR AN IMAGE')),
                ('ipfsHash', models.CharField(max_length=128, null=True)),
                ('ipfsAddress', models.CharField(max_length=128, null=True)),
                ('transactionHash', models.CharField(max_length=128, null=True)),
                ('blockHash', models.CharField(max_length=128, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
