# Generated by Django 3.0.5 on 2021-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0003_auto_20210413_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.TextField(default='["image"]'),
        ),
    ]
