# Generated by Django 3.0.5 on 2021-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0004_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='similar',
            name='ipfsHash',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
