# Generated by Django 3.0.5 on 2021-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0006_auto_20210416_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
